### ISSUE TITLE
ethnode openethereum returned 404 downloading openethereum

### ISSUE THREAD

**Issue by fabianorodrigo** [vrde/ethnode#13]
Hi!

I execute this command as the instructions say:  
`ethnode openethereum  --workdir=/some/path  
`
and got this:

Download latest openethereum version, please wait.
```
Downloading https://github.com/openethereum/openethereum/releases/download/v3.0.1/openethereum-linux-v3.0.1.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Error downloading openethereum, this might be temporary, try again later.
```

**Comment by vrde** [comment]
Hi @fabianorodrigo, thank you for the issue. The openethereum team removed version 3.0.1, so the download was actually broken. I've just published ethnode 0.0.24 on NPM, can you please try again? Thanks!
