### ISSUE TITLE
ethnode parity sometimes doesn't shutdown parity on ctrl+c

### ISSUE THREAD

**Issue by TimDaub** [vrde/ethnode#2]

**Comment by vrde** [comment]
I've opened an issue in the [parity repo](https://github.com/paritytech/parity-ethereum/issues/10378).

**Comment by vrde** [comment]
Still waiting for Parity...

**Comment by vrde** [comment]
https://github.com/openethereum/parity-ethereum/issues/10378#event-3590445551
