### ISSUE TITLE
Multiple predifined accounts

### ISSUE THREAD

**Issue by srcCraftsman** [vrde/ethnode#28]
Is there any convenient way to generate large amount of accounts(~10 000) with predefined balance? 
I've tried to use `geth account new` to generate account keys and put it into 'keys' folder, but it worked only until big amount of accounts. At 25 accounts it already stucks for several minutes during the start, at 600 it's impossible to wait until start(

**Comment by vrde** [comment]
I'd suggest to:

- Increase the initial balance of the 10 "root" accounts (the ones in the genesis file);
- Generate 10,000 accounts (I'd use a HD approach, so you can easily select one of these 10,000 accounts just by using an index).
- Run a script that distributes the funds to these 10,000 accounts.

It will take a while, you can try to parallelize the transfers.

**Comment by vrde** [comment]
If you start ethnode with `-w, --workdir <dir>` you can also stop the node after you've finished the transfers, copy the working dir somewhere else and use it as a snapshot. Does it make sense?

**Comment by TessTea** [comment]
> If you start ethnode with `-w, --workdir <dir>` you can also stop the node after you've finished the transfers, copy the working dir somewhere else and use it as a snapshot. Does it make sense?
Sorry, missed your reply(

**Comment by srcCraftsman** [comment]
> If you start ethnode with `-w, --workdir <dir>` you can also stop the node after you've finished the transfers, copy the working dir somewhere else and use it as a snapshot. Does it make sense?



Sorry, missed your reply(
I've managed to generate 5,000 users using `geth account new`, get all private keys from generated files and then put it into `genesis.geth.json` with premined 1000 ETH. It was enough to solve my task.
If you want, I can create a PR with predefined 5K users)

**Comment by vrde** [comment]
You can also share the script you used to generate these addresses. I can include it in a `script` directory. Doesn't need to be perfect :)

**Comment by srcCraftsman** [comment]
> You can also share the script you used to generate these addresses. I can include it in a `script` directory. Doesn't need to be perfect :)


Sure, if you want! But whole generating process in this case took about 10 hours for 5000 wallets, so I think it'd be better to look for more convenient way, if we want to set amount of predefined accounts during start

**Comment by vrde** [comment]
That took quite long actually. I guess we can skip an PR for now and—if anyone needs it in the future—look for a more performant solution. Thanks for sharing your insights :)
