### ISSUE TITLE
Event logs do not work

### ISSUE THREAD

**Issue by TimDaub** [vrde/ethnode#4]
I'm specifically talking about `contract.getPastEvents`, like ganache-cli, it seems geth doesn't store these. Or at least when running these commands nothing is returned.

One example where this is needed is my project here: https://github.com/TimDaub/ERC721-wallet/blob/master/src/sagas/fetchTransactions.js#L89

I googled around already but couldn't find an option for geth to enable them 🤷‍♂️

**Comment by vrde** [comment]
Not sure how to approach this. I tried `getPastEvents` manually with this contract:

```solidity
pragma solidity >=0.4.21 <0.6.0;

contract Events {
  event Something(address _from);

  function foo() public {
    emit Something(msg.sender);
  }
}
```

and this code:
```node
const Web3 = require("web3");
const Web3Utils = require("web3-utils");
const web3 = new Web3("http://localhost:8545/");
const metadata = require("./build/contracts/Events.json");

async function main() {
  const [alice] = await web3.eth.getAccounts();
  const contract = new web3.eth.Contract(
    metadata.abi,
    metadata.networks[await web3.eth.net.getId()].address
  );

  contract.methods.foo().send({ from: alice });
  contract.getPastEvents("Something", console.log);
}

main().catch(console.error);
```

Everything works as expected.

**Comment by vrde** [comment]
I'll close this for now. Feel free to reopen the issue if it still doesn't work, thanks!
