### ISSUE TITLE
ERROE npm install -g ethnode ethnode

### ISSUE THREAD

**Issue by yeeacksonideo** [vrde/ethnode#7]
ethnode@0.0.18 postinstall: `./cli.js -d`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ethnode@0.0.18 postinstall script './cli.js -d'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ethnode package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./cli.js -d
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ethnode
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ethnode
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/a/npm-debug.log
npm ERR! code 1

**Comment by vrde** [comment]
Which version of node are you using and on which system?

**Comment by vrde** [comment]
I'll close this for now. Feel free to comment again if you want :)
